### ISSUE TITLE
Lotus::Action should not dump the exception if the exception is handled

### ISSUE THREAD

**Issue by weppos** [lotus/controller#74]
Given the following action

```ruby
class Show
  include Api::V2::Action

  handle_exception RecordNotFound => :handle_record_not_found

  def call(params)
    # ...
  end

  def handle_record_not_found(exception)
    halt(404, { message: exception.message }.to_json)
  end
end
```

An HTTP request for an invalid resource will correctly render the error message

```
{"message":"Domain `3999' not found"}
```

However, the exception is also dumped in the log

```
ActiveRecord::RecordNotFound: Domain `3999' not found
  ...
  ...
  ...
  /Users/weppos/.rvm/gems/ruby-2.1.5@dnsimple/gems/lotus-controller-0.3.1/lib/lotus/action/callbacks.rb:149:in `call'
  /Users/weppos/.rvm/gems/ruby-2.1.5@dnsimple/gems/lotus-controller-0.3.1/lib/lotus/action/callable.rb:73:in `block in call'
  /Users/weppos/.rvm/gems/ruby-2.1.5@dnsimple/gems/lotus-controller-0.3.1/lib/lotus/action/throwable.rb:104:in `block in _rescue'
  /Users/weppos/.rvm/gems/ruby-2.1.5@dnsimple/gems/lotus-controller-0.3.1/lib/lotus/action/throwable.rb:102:in `catch'
  /Users/weppos/.rvm/gems/ruby-2.1.5@dnsimple/gems/lotus-controller-0.3.1/lib/lotus/action/throwable.rb:102:in `_rescue'
```

making it hard to distinguish handled vs not-handled exceptions. That's because `_rescue` always dumps the error, no matter if it was handled or not.

```ruby
      def _rescue
        catch :halt do
          begin
            yield
          rescue => exception
            _reference_in_rack_errors(exception)
            _handle_exception(exception)
          end
        end
      end
```

My proposal is to dump the exception only if not handled. Though?

**Comment by jodosha** [comment]
@weppos Good catch. I agree :+1:
